export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'FETCH_USERS_FAILURE'

export const GET_ALL_USERS_WATCHER='GET_ALL_USERS'