export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'FETCH_USERS_FAILURE'
export const EDIT_USER_SUCCESS='EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED='EDIT_USER_FAILED'

export const GET_ALL_USERS_WATCHER='GET_ALL_USERS'
export const EDIT_USER_WATCHER='EDIT_USER_WATCHER'


